# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

darkmode: false

# Personal info
name: Saim Mehmood
title: MSc in Computer Science | Data Science | Machine Learning
email: saim(dot)mehmood(dot)gul(at)gmail.com
#phone: +1 (847) 641-4612
#website: saimmemhmood.com

# Social links
# twitter_username: facespics
github_username:  saimmehmood
# dribbble_username: jekyll
#medium_username: saim.mehmood.gul
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: saimmehmoodgul
#stackoverflow_username: 4044015//saim-mehmood
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/circle-cropped.png
about_content: | # this will include new lines to allow paragraphs
    My background is in data mining and machine learning with applied research experience working at the [Data Mining Lab](https://dminer.eecs.yorku.ca/), York University.
    My most recent experience was working as an MLOps Engineer at a Google Cloud Platform (GCP) consulting company where I leveraged GCP ML stack to deliver end-to-end machine learning models. 
    I'm certified as a GCP Professional Machine Learning Engineer.
    
    I have experience working with Geo-Spatial Data sets for which I used PostgreSQL & PostGIS and Python to extract insights.
    I typically visualize data sets along the way to understand the pipelines and models I'm creating.
    
    
    I conducted research as an Erasmus Scholar @ the Department of Information Technology, Uppsala University, Sweden in the area of Cloud Computing. 
    
    During my graduate studies at York University, I was working under the supervision of [Prof. Manos Papagelis](https://www.eecs.yorku.ca/~papaggel/).

    **Interests:** data mining, machine learning, data science, natural language processing (NLP), cloud computing

    **Technical Knowledge and Skills:** 
    
    • Data Mining & Visualization   \t  Python (matplotlib, seaborn, pandas, numpy), Power BI

    • Programming Languages                       Python, Java, C#, C/C++   
    Python (pandas, numpy, scikit-learn, networkx, seaborn, matplotlib), Deep Learning (node2vec, word2vec, graph embeddings), NLP (spacy, transformers), PostgreSQL/PostGIS, MATLAB, Google Cloud Platform (Places & Directions APIs), Java, C#, Tensorflow, Spark, Colab, LaTeX, C++

    [• Medium Profile](https://saim-mehmood-gul.medium.com/)

    [• Stackoverflow Profile](https://stackoverflow.com/users/4044015/saim-mehmood)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certificate Section
# certificate_title: Certifications

# Volunteer Section
# volunteer_title: Volunteer

# More Section
# more_title: Honors and Awards
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data mining and software engineering I earned some awards:
   - Awarded York University Graduate Fellowship for the entire duration of M.Sc. Computer Science, January 2018
   - Electrical Engineering and Computer Science Graduate Student Association (EECS-GSA) York University, Vice-President Organization, Sep 2018 - 2019
   - Represented Pakistani youth in China, Pakistan Youth Delegation, August 2016
   - Won Erasmus Mundus Exchange Scholarship to spend an exchange semester at Uppsala University, May 2015 
   - Winner 17th In-House Speed Programming Competition, University of the Punjab, May 2015

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
