# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

darkmode: false

# Personal info
name: Saim Mehmood
title: Data Scientist | Python | Quantum Computing nerd
email: saim.mehmood.gul(at)gmail.com
phone: +1 (469) 643-3148
#website: saimmemhmood.com

# Social links
# twitter_username: facespics
github_username:  saimmehmood
# dribbble_username: jekyll
#medium_username: saim.mehmood.gul
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: saimmehmoodgul
#stackoverflow_username: 4044015//saim-mehmood
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/circle-cropped.png
about_content: | # this will include new lines to allow paragraphs
    A recent graduate of MSc in computer science with 2 plus years of applied research experience working at the 
    [Data Mining Lab](http://dminer.eecs.yorku.ca/) @ Lassonde School of Engineering, York University Toronto. 
    I did my bachelor's in software engineering from University of the Punjab, Lahore.
    
    I have experience working with Geo-Spatial Data sets for which I used PostgreSQL & PostGIS and Python to extract insights.
    I typically visualize data sets along the way to understand the pipelines and models I'm creating.
    
    
    I conducted research as an Erasmus Scholar @ the Department of Information Technology, Uppsala University, Sweden in the area of Cloud Computing. 
    
    During my graduate studies at York University, I was working under the supervision of [Prof. Manos Papagelis](https://www.eecs.yorku.ca/~papaggel/).

    **Interests:** data mining, graph mining, trajectory data mining, machine learning, big data analytics, data science

    **Skills:** <mark>Python (pandas, numpy, scikit-learn, networkx, seaborn, matplotlib), NLP (node2vec, word2vec, graph embeddings), PostgreSQL, PostGIS, MATLAB, GCP (Places & Directions APIs), Java, C#, TensorFlow, Spark, Colab, LaTeX </mark>

    [-> Link to Medium Profile](https://saim-mehmood-gul.medium.com/)

    [-> Link to Stackoverflow Profile](https://stackoverflow.com/users/4044015/saim-mehmood)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certificate Section
# certificate_title: Certifications

# More Section
# more_title: Honors and Awards
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data mining and software engineering I earned some awards:
   - Awarded York University Graduate Fellowship for the entire duration of M.Sc. Computer Science, January 2018
   - Represented Pakistani youth in China, Pakistan Youth Delegation, August 2016
   - Won Erasmus Mundus Exchange Scholarship to spend an exchange semester at Uppsala University, May 2015 
   - Winner 17th In-House Speed Programming Competition, University of the Punjab, May 2015

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
