# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

darkmode: false

# Personal info
name: Saim Mehmood
title: Data Engineer | Python
email: saim.mehmood.gul@gmail.com
phone: (437) 998-9171
#website: saimmemhmood.com

# Social links
# twitter_username: facespics
github_username:  saimmehmood
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: saimmehmoodgul
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/circle-cropped.png
about_content: | # this will include new lines to allow paragraphs
  I am a young researcher working in the field of Data Mining with 2 years of experience working at the 
    [Data Mining Lab](https://dminer.eecs.yorku.ca/) @ Lassonde School of Engineering, York University Toronto. 
    I love working with Spatial Data sets for which I use PostgreSQL & PostGIS and Python to extract insights.
    I typically visualize data sets along the way to understand the pipelines and models I'm creating.
    
    
    I have also worked on a project related to Cloud Computing @ Uppsala University, Sweden. 
    
    Currently I'm working under the supervision [Prof. Manos Papagelis](https://www.eecs.yorku.ca/~papaggel/).

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]