# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

darkmode: false

# Personal info
name: Saim Mehmood
title: AI & Data Professional | 5+ yrs in AI/ML, Data Engineering & Software Dev | GCP Certified ML Engineer | Experience in Finance, Real Estate & Utilities | Award-Winning IEEE-Published Researcher
email: saim(dot)mehmood(dot)gul(at)gmail.com
#phone: +1 (847) 641-4612
#website: saimmemhmood.com

# Social links
# twitter_username: facespics
github_username:  saimmehmood
# dribbble_username: jekyll
#medium_username: saim.mehmood.gul
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: saimmehmoodgul
#stackoverflow_username: 4044015//saim-mehmood
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/circle-cropped.png
about_content: | # this will include new lines to allow paragraphs
    AI and Data Professional with 5+ years of experience delivering data-driven solutions in **AI/ML, Data
    Engineering, and Software Development** across diverse industries including **financial services, real estate,
    and utilities** across North America. Certified **Google Cloud Professional Machine Learning Engineer**,
    holding an MSc in Computer Science (York University) and a BSc in Software Engineering. Applied research
    experience at the **Data Mining Lab, York University**, with **award-winning work published at the IEEE MDM
    Conference (Versailles, France)**. Internationally recognized through EU funding to complete Bachelor's thesis
    project at **Uppsala University, Sweden**. Proven ability to design and deploy scalable ML/AI models, implement
    analytics pipelines, and collaborate with stakeholders to drive measurable business impact.
    
    
    I conducted research as an Erasmus Scholar @ the Department of Information Technology, Uppsala University, Sweden in the area of Cloud Computing. 
    
    During my graduate studies at York University, I was working under the supervision of [Prof. Manos Papagelis](https://www.eecs.yorku.ca/~papaggel/).

    **Interests:** data mining, machine learning, data science, natural language processing (NLP), cloud computing, Agentic AI, LLMs, RAG, etc.

    **Tools utilized and experimented with:** 
    
    • Data Mining & Visualization - Python (matplotlib, seaborn, pandas, numpy), PySpark, Power BI/Tableau

    • Programming Languages - Python, Java, C#, C/C++, JavaScript/TypeScript
   
    • Databases - PostgreSQL/PostGIS, MongoDB, MySQL, Oracle

    • Google Cloud Platform (GCP) - Vertex AI, BigQuery, Dataflow

    • NLP & Machine Learning - spaCY, NLTK, Tensorflow/PyTorch/Keras

    • Operating Systems - Linux/Mac, Windows
    
    [• Medium Profile](https://saim-mehmood-gul.medium.com/)

    [• Stackoverflow Profile](https://stackoverflow.com/users/4044015/saim-mehmood)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certificate Section
# certificate_title: Certifications

# Volunteer Section
# volunteer_title: Volunteer

# More Section
# more_title: Honors and Awards
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data mining and software engineering I earned some awards:
   - Awarded York University Graduate Fellowship for the entire duration of M.Sc. Computer Science, January 2018
   - Electrical Engineering and Computer Science Graduate Student Association (EECS-GSA) York University, Vice-President Organization, Sep 2018 - 2019
   - Represented Pakistani youth in China, Pakistan Youth Delegation, August 2016
   - Won Erasmus Mundus Exchange Scholarship to spend an exchange semester at Uppsala University, May 2015 
   - Winner 17th In-House Speed Programming Competition, University of the Punjab, May 2015

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
